### Get All Commands
GET http://localhost:3000/command

### Get Command by Command

GET http://localhost:3000/command/cmd/%2Fhi1

### Get Command by ID 
GET http://localhost:3000/command/6802a6659fdb9ae382d7e029


### Create Command
POST http://localhost:3000/command
Content-Type: application/json

{
    "name": "enzo2",
    "command": "/enzo2",
    "text": "Hi Enzo, thanks for reaching out to F1RST Delivery Support. Only customers and restaurants can reach out the driver. Please let the customer to call the driver using this info XXX-XXX-XXXX and the code [CODE] after dialing the number. In case you want to, you can use the dinner-to-runner phone number and same code to call the driver. Should you encounter any issues during this process, please don’t hesitate to let me know—I’ll be more than happy to assist you further." 
}



### Update Command

PATCH http://localhost:3000/command/6802a6659fdb9ae382d7e029
Content-Type: application/json

{

    "text": "Welcome to the chat"
}

### Delete Command

DELETE http://localhost:3000/command/67fe9cb7e071a32a40d2076e


