### Get All Commands
GET http://localhost:3000/command

### Get Command by Command

GET http://localhost:3000/command/cmd/%2Fhi1

### Get Command by ID 
GET http://localhost:3000/command/6802a6659fdb9ae382d7e029


### Create Command
POST http://localhost:3000/command
Content-Type: application/json

{
    "name": "ezra1",
    "command": "/ezra1",
    "text": "Hi Ezra, thanks for reaching out to F1RST Delivery Support!  Please note that we are only able to assign fleets, not individual drivers. In this case, I can confirm that the DSP is actively working on assigning a driver to this/these order(s), as an alternative we can duplicate the order to assign it to a different fleet and exhaust all the options. We truly appreciate your patience and understanding as we ensure the best possible service." 
}



### Update Command

PATCH http://localhost:3000/command/6802a6659fdb9ae382d7e029
Content-Type: application/json

{

    "text": "Welcome to the chat"
}

### Delete Command

DELETE http://localhost:3000/command/67fe9cb7e071a32a40d2076e


