### Get All Commands
GET http://localhost:3000/command

### Get Command by Command

GET http://localhost:3000/command/command/%2Fhi1

### Get Command by ID 
GET http://localhost:3000/command/67fd65a137d19e2aca8af4e6


### Create Command
POST http://localhost:3000/command
Content-Type: application/json

{
    "name": "hi2",
    "command": "/hi2",
    "text": "Welcome to the bot"
}

### Update Command

PATCH http://localhost:3000/command/command/67fe9cb7e071a32a40d2076e
Content-Type: application/json

{

    "text": "Welcome to the chat"
}


